stages:
  startup:
    cmd: 
    - mlflow server --host 127.0.0.1 --port 5000
    - uvicorn backend.app:app --reload
    - cd frontend/frontend_side_effect_predictor
    - npm start
    - cd ..
    - cd ..
    - #prometheus startup
    - #grafana startup


  prepare:
    cmd: python -m backend.ml_models.prepare
    deps:
    - backend/ml_models/config.py
    - backend/ml_models/prepare.py
    - backend/target/params.yaml
    outs:
    - backend/target/temp_targets/X_train_master.pkl
    - backend/target/temp_targets/Y_train_master.pkl
    - backend/target/temp_targets/auc_all_runs.pkl
    - backend/target/temp_targets/fpr_list.pkl
    - backend/target/temp_targets/tpr_list.pkl
  predict_SE:
    cmd: python -m backend.ml_models.predict_SE
    deps:
    - backend/ml_models/config.py
    - backend/ml_models/predict_SE.py
    - backend/target/inputted_features.pkl
    - backend/target/params.yaml
    - backend/target/temp_targets/X_train_master.pkl
    - backend/target/temp_targets/Y_train_master.pkl
    - backend/target/temp_targets/auc_all_runs.pkl
    - backend/target/temp_targets/fpr_list.pkl
    - backend/target/temp_targets/tpr_list.pkl
    outs:
    - backend/target/output.pkl
  train_AMPP:
    cmd: python -m backend.ml_models.train_AMPP
    deps:
    - backend/ml_models/config.py
    - backend/ml_models/prepare.py
    - backend/ml_models/train_AMPP.py
    - backend/target/temp_targets/X_train_master.pkl
    - backend/target/temp_targets/Y_train_master.pkl
    - backend/target/temp_targets/auc_all_runs.pkl
    - backend/target/temp_targets/fpr_list.pkl
    - backend/target/temp_targets/tpr_list.pkl
    outs:
    - backend/models/AMPP_temp.pkl


  predict_AMPP:
    cmd:
    - python -m backend.ml_models.drift_monitor 

    - python -m backend.ml_models.predict_AMPP 

    deps:
    - backend/ml_models/config.py
    - backend/ml_models/drift_monitor.py
    - backend/ml_models/predict_AMPP.py
    - backend/target/inputted_features_2.pkl
    - backend/target/temp_targets/X_train_master.pkl

    outs:
    - backend/target/ampp_predictions.pkl
    - backend/target/drift_status.txt
