groups:
  - name: drift_monitoring
    rules:
      - alert: DataDriftDetected
        expr: increase(data_drift_alerts_total[1m]) > 0
        labels:
          severity: warning
        annotations:
          summary: "⚠️ Data Drift Detected"
          description: "Drift detection counter has increased in the past minute."
